# .github/labview-ci.yml - LabVIEW CI configuration
# Updated by the Reconfigure workflow.
schemaVersion: 1
installedVersion: 4.13.0
configuredAt: 2026-07-30T19:55:34Z
source:
  repo: danielcoons/LabVIEW-CLI-testing
  ref: v4.13.0
config:
  labviewVersion: "2026"
  os: [windows, linux]
  concurrency:
    maxParallel: 5
  container:
    use: latest
    vipc:
      - path: ".github/labview/vipm/ci-tooling.vipc"
        monitor: true
activities:
  - dashboard
  - masscompile
  - vi-analyzer
  - vidiff
  - snapshots
  - custom-image
  - snapshots-2
  - unit-tests
  - builds
  - sbom
